// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/server/service.proto

package server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameResultEnum int32

const (
	GameResultEnum_Win  GameResultEnum = 0
	GameResultEnum_Loss GameResultEnum = 1
)

var GameResultEnum_name = map[int32]string{
	0: "Win",
	1: "Loss",
}

var GameResultEnum_value = map[string]int32{
	"Win":  0,
	"Loss": 1,
}

func (x GameResultEnum) String() string {
	return proto.EnumName(GameResultEnum_name, int32(x))
}

func (GameResultEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{0}
}

type SymbolEnum int32

const (
	SymbolEnum_Circle SymbolEnum = 0
	SymbolEnum_Cross  SymbolEnum = 1
)

var SymbolEnum_name = map[int32]string{
	0: "Circle",
	1: "Cross",
}

var SymbolEnum_value = map[string]int32{
	"Circle": 0,
	"Cross":  1,
}

func (x SymbolEnum) String() string {
	return proto.EnumName(SymbolEnum_name, int32(x))
}

func (SymbolEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{1}
}

type MoveResultEnum int32

const (
	MoveResultEnum_Ok    MoveResultEnum = 0
	MoveResultEnum_Retry MoveResultEnum = 1
	MoveResultEnum_Error MoveResultEnum = 2
)

var MoveResultEnum_name = map[int32]string{
	0: "Ok",
	1: "Retry",
	2: "Error",
}

var MoveResultEnum_value = map[string]int32{
	"Ok":    0,
	"Retry": 1,
	"Error": 2,
}

func (x MoveResultEnum) String() string {
	return proto.EnumName(MoveResultEnum_name, int32(x))
}

func (MoveResultEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{2}
}

type JoinResult struct {
	Result               bool       `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Token                string     `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Info                 string     `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Symbol               SymbolEnum `protobuf:"varint,4,opt,name=symbol,proto3,enum=SymbolEnum" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JoinResult) Reset()         { *m = JoinResult{} }
func (m *JoinResult) String() string { return proto.CompactTextString(m) }
func (*JoinResult) ProtoMessage()    {}
func (*JoinResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{0}
}

func (m *JoinResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResult.Unmarshal(m, b)
}
func (m *JoinResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResult.Marshal(b, m, deterministic)
}
func (m *JoinResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResult.Merge(m, src)
}
func (m *JoinResult) XXX_Size() int {
	return xxx_messageInfo_JoinResult.Size(m)
}
func (m *JoinResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResult.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResult proto.InternalMessageInfo

func (m *JoinResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *JoinResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinResult) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *JoinResult) GetSymbol() SymbolEnum {
	if m != nil {
		return m.Symbol
	}
	return SymbolEnum_Circle
}

type UpdateGameStateResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGameStateResult) Reset()         { *m = UpdateGameStateResult{} }
func (m *UpdateGameStateResult) String() string { return proto.CompactTextString(m) }
func (*UpdateGameStateResult) ProtoMessage()    {}
func (*UpdateGameStateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{1}
}

func (m *UpdateGameStateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGameStateResult.Unmarshal(m, b)
}
func (m *UpdateGameStateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGameStateResult.Marshal(b, m, deterministic)
}
func (m *UpdateGameStateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGameStateResult.Merge(m, src)
}
func (m *UpdateGameStateResult) XXX_Size() int {
	return xxx_messageInfo_UpdateGameStateResult.Size(m)
}
func (m *UpdateGameStateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGameStateResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGameStateResult proto.InternalMessageInfo

type YourMoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YourMoveResult) Reset()         { *m = YourMoveResult{} }
func (m *YourMoveResult) String() string { return proto.CompactTextString(m) }
func (*YourMoveResult) ProtoMessage()    {}
func (*YourMoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{2}
}

func (m *YourMoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YourMoveResult.Unmarshal(m, b)
}
func (m *YourMoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YourMoveResult.Marshal(b, m, deterministic)
}
func (m *YourMoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YourMoveResult.Merge(m, src)
}
func (m *YourMoveResult) XXX_Size() int {
	return xxx_messageInfo_YourMoveResult.Size(m)
}
func (m *YourMoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_YourMoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_YourMoveResult proto.InternalMessageInfo

type GameFinishedResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameFinishedResult) Reset()         { *m = GameFinishedResult{} }
func (m *GameFinishedResult) String() string { return proto.CompactTextString(m) }
func (*GameFinishedResult) ProtoMessage()    {}
func (*GameFinishedResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{3}
}

func (m *GameFinishedResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFinishedResult.Unmarshal(m, b)
}
func (m *GameFinishedResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFinishedResult.Marshal(b, m, deterministic)
}
func (m *GameFinishedResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFinishedResult.Merge(m, src)
}
func (m *GameFinishedResult) XXX_Size() int {
	return xxx_messageInfo_GameFinishedResult.Size(m)
}
func (m *GameFinishedResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFinishedResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameFinishedResult proto.InternalMessageInfo

type GameResult struct {
	Result               GameResultEnum `protobuf:"varint,1,opt,name=result,proto3,enum=GameResultEnum" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GameResult) Reset()         { *m = GameResult{} }
func (m *GameResult) String() string { return proto.CompactTextString(m) }
func (*GameResult) ProtoMessage()    {}
func (*GameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{4}
}

func (m *GameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResult.Unmarshal(m, b)
}
func (m *GameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResult.Marshal(b, m, deterministic)
}
func (m *GameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResult.Merge(m, src)
}
func (m *GameResult) XXX_Size() int {
	return xxx_messageInfo_GameResult.Size(m)
}
func (m *GameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameResult proto.InternalMessageInfo

func (m *GameResult) GetResult() GameResultEnum {
	if m != nil {
		return m.Result
	}
	return GameResultEnum_Win
}

type Position struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{5}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Position) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type MoveResult struct {
	Result               MoveResultEnum `protobuf:"varint,1,opt,name=result,proto3,enum=MoveResultEnum" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MoveResult) Reset()         { *m = MoveResult{} }
func (m *MoveResult) String() string { return proto.CompactTextString(m) }
func (*MoveResult) ProtoMessage()    {}
func (*MoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{6}
}

func (m *MoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResult.Unmarshal(m, b)
}
func (m *MoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResult.Marshal(b, m, deterministic)
}
func (m *MoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResult.Merge(m, src)
}
func (m *MoveResult) XXX_Size() int {
	return xxx_messageInfo_MoveResult.Size(m)
}
func (m *MoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResult proto.InternalMessageInfo

func (m *MoveResult) GetResult() MoveResultEnum {
	if m != nil {
		return m.Result
	}
	return MoveResultEnum_Ok
}

type ReconnectData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReconnectData) Reset()         { *m = ReconnectData{} }
func (m *ReconnectData) String() string { return proto.CompactTextString(m) }
func (*ReconnectData) ProtoMessage()    {}
func (*ReconnectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{7}
}

func (m *ReconnectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReconnectData.Unmarshal(m, b)
}
func (m *ReconnectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReconnectData.Marshal(b, m, deterministic)
}
func (m *ReconnectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReconnectData.Merge(m, src)
}
func (m *ReconnectData) XXX_Size() int {
	return xxx_messageInfo_ReconnectData.Size(m)
}
func (m *ReconnectData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReconnectData.DiscardUnknown(m)
}

var xxx_messageInfo_ReconnectData proto.InternalMessageInfo

func (m *ReconnectData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReconnectResult struct {
	Result               bool       `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Text                 string     `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Board                []byte     `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Symbol               SymbolEnum `protobuf:"varint,4,opt,name=symbol,proto3,enum=SymbolEnum" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReconnectResult) Reset()         { *m = ReconnectResult{} }
func (m *ReconnectResult) String() string { return proto.CompactTextString(m) }
func (*ReconnectResult) ProtoMessage()    {}
func (*ReconnectResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c052f80bbbcc317f, []int{8}
}

func (m *ReconnectResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReconnectResult.Unmarshal(m, b)
}
func (m *ReconnectResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReconnectResult.Marshal(b, m, deterministic)
}
func (m *ReconnectResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReconnectResult.Merge(m, src)
}
func (m *ReconnectResult) XXX_Size() int {
	return xxx_messageInfo_ReconnectResult.Size(m)
}
func (m *ReconnectResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReconnectResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReconnectResult proto.InternalMessageInfo

func (m *ReconnectResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ReconnectResult) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ReconnectResult) GetBoard() []byte {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *ReconnectResult) GetSymbol() SymbolEnum {
	if m != nil {
		return m.Symbol
	}
	return SymbolEnum_Circle
}

func init() {
	proto.RegisterEnum("GameResultEnum", GameResultEnum_name, GameResultEnum_value)
	proto.RegisterEnum("SymbolEnum", SymbolEnum_name, SymbolEnum_value)
	proto.RegisterEnum("MoveResultEnum", MoveResultEnum_name, MoveResultEnum_value)
	proto.RegisterType((*JoinResult)(nil), "JoinResult")
	proto.RegisterType((*UpdateGameStateResult)(nil), "UpdateGameStateResult")
	proto.RegisterType((*YourMoveResult)(nil), "YourMoveResult")
	proto.RegisterType((*GameFinishedResult)(nil), "GameFinishedResult")
	proto.RegisterType((*GameResult)(nil), "GameResult")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*MoveResult)(nil), "MoveResult")
	proto.RegisterType((*ReconnectData)(nil), "ReconnectData")
	proto.RegisterType((*ReconnectResult)(nil), "ReconnectResult")
}

func init() {
	proto.RegisterFile("pkg/server/service.proto", fileDescriptor_c052f80bbbcc317f)
}

var fileDescriptor_c052f80bbbcc317f = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0x6d, 0xa1, 0x74, 0xe1, 0xb2, 0x96, 0xe6, 0xba, 0x22, 0xc1, 0x17, 0x52, 0x62, 0x24, 0x9b,
	0x38, 0x24, 0xe8, 0xfa, 0x01, 0xae, 0x68, 0x62, 0xdc, 0xb8, 0xe9, 0xc6, 0x18, 0x7d, 0x2b, 0x30,
	0x8b, 0x0d, 0xed, 0x0c, 0x99, 0x4e, 0xd7, 0xe5, 0x2f, 0xfc, 0x0f, 0x7f, 0xd2, 0xcc, 0x4c, 0xbb,
	0xa5, 0x04, 0xa3, 0x4f, 0xdc, 0x73, 0xef, 0x1d, 0xce, 0xcc, 0x39, 0xa7, 0x30, 0xd8, 0x6e, 0xd6,
	0xd3, 0x8c, 0x8a, 0x3b, 0x2a, 0xf4, 0x4f, 0xbc, 0xa4, 0x64, 0x2b, 0xb8, 0xe4, 0xc3, 0x67, 0x6b,
	0xce, 0xd7, 0x09, 0x9d, 0x6a, 0xb4, 0xc8, 0x6f, 0xa7, 0x34, 0xdd, 0xca, 0x9d, 0x19, 0x06, 0x19,
	0xc0, 0x47, 0x1e, 0xb3, 0x90, 0x66, 0x79, 0x22, 0xb1, 0x0f, 0xae, 0xd0, 0xd5, 0xc0, 0x1e, 0xd9,
	0x93, 0x76, 0x58, 0x20, 0x3c, 0x83, 0x96, 0xe4, 0x1b, 0xca, 0x06, 0x8d, 0x91, 0x3d, 0xe9, 0x84,
	0x06, 0x20, 0x82, 0x13, 0xb3, 0x5b, 0x3e, 0x68, 0xea, 0xa6, 0xae, 0x71, 0x0c, 0x6e, 0xb6, 0x4b,
	0x17, 0x3c, 0x19, 0x38, 0x23, 0x7b, 0xe2, 0xcd, 0xba, 0xe4, 0x46, 0xc3, 0x39, 0xcb, 0xd3, 0xb0,
	0x18, 0x05, 0x4f, 0xe1, 0xc9, 0x97, 0xed, 0x2a, 0x92, 0xf4, 0x43, 0x94, 0xd2, 0x1b, 0x19, 0x49,
	0x6a, 0xf8, 0x03, 0x1f, 0xbc, 0x6f, 0x3c, 0x17, 0x57, 0xfc, 0xae, 0xec, 0x9c, 0x01, 0xaa, 0xa5,
	0xf7, 0x31, 0x8b, 0xb3, 0x1f, 0x74, 0x55, 0x74, 0x2f, 0x00, 0x54, 0xb7, 0xb8, 0xf5, 0x8b, 0xda,
	0xad, 0xbd, 0x59, 0x8f, 0x54, 0x43, 0xc3, 0x6b, 0xc6, 0xc1, 0x6b, 0x68, 0x5f, 0xf3, 0x2c, 0x96,
	0x31, 0x67, 0xe8, 0x43, 0x53, 0xf0, 0x9f, 0xfa, 0x44, 0x2b, 0x54, 0xa5, 0x7a, 0xfc, 0x92, 0x27,
	0x79, 0x6a, 0x5e, 0xd9, 0x0a, 0x0b, 0xa4, 0xc8, 0xaa, 0x0b, 0x1d, 0x21, 0xab, 0x86, 0x35, 0xb2,
	0xe7, 0xf0, 0x28, 0xa4, 0x4b, 0xce, 0x18, 0x5d, 0xca, 0x77, 0x91, 0x8c, 0x2a, 0x11, 0xed, 0x3d,
	0x11, 0x83, 0x7b, 0xe8, 0x3d, 0xac, 0xfd, 0xc3, 0x05, 0x04, 0x47, 0xd2, 0x7b, 0x59, 0x98, 0xa0,
	0x6b, 0xf5, 0xa7, 0x0b, 0x1e, 0x89, 0x95, 0x36, 0xe1, 0x34, 0x34, 0xe0, 0xbf, 0x5c, 0x38, 0x1f,
	0x83, 0x57, 0xd7, 0x09, 0x4f, 0xa0, 0xf9, 0x35, 0x66, 0xbe, 0x85, 0x6d, 0x70, 0x3e, 0xf1, 0x2c,
	0xf3, 0xed, 0xf3, 0x31, 0x40, 0x75, 0x14, 0x01, 0xdc, 0xcb, 0x58, 0x2c, 0x13, 0xea, 0x5b, 0xd8,
	0x81, 0xd6, 0xa5, 0x30, 0x4b, 0x04, 0xbc, 0xba, 0x08, 0xe8, 0x42, 0xe3, 0xf3, 0xc6, 0x2c, 0x85,
	0x54, 0x8a, 0x9d, 0x6f, 0xab, 0x72, 0x2e, 0x04, 0x17, 0x7e, 0x63, 0xf6, 0xcb, 0x86, 0x53, 0x45,
	0x9d, 0x5d, 0x45, 0x2c, 0x5a, 0x53, 0x81, 0x2f, 0xc1, 0x51, 0x29, 0xc4, 0x3e, 0x31, 0x59, 0x25,
	0x65, 0x56, 0xc9, 0x5c, 0x65, 0x75, 0xd8, 0x25, 0x55, 0x48, 0x03, 0x0b, 0x47, 0xe0, 0x28, 0x3e,
	0xec, 0x90, 0xd2, 0xce, 0x61, 0x77, 0xcf, 0x86, 0xc0, 0xc2, 0x29, 0x74, 0x1e, 0x54, 0x45, 0x8f,
	0xd4, 0x8c, 0x18, 0xfa, 0xe4, 0x40, 0xf1, 0xc0, 0x9a, 0xfd, 0xb6, 0xc1, 0xbd, 0x4e, 0xa2, 0x1d,
	0x15, 0xf8, 0x06, 0x7a, 0x07, 0xe9, 0xdc, 0x27, 0xea, 0x93, 0xe3, 0xd1, 0xb5, 0xf0, 0x02, 0xda,
	0x65, 0x78, 0xff, 0xfa, 0x90, 0x1e, 0x39, 0xc8, 0xb7, 0x85, 0x33, 0xa3, 0x45, 0x99, 0x70, 0xec,
	0xee, 0xa5, 0x77, 0xf8, 0x98, 0x1c, 0x49, 0xbf, 0xf5, 0xb6, 0xf3, 0xfd, 0xa4, 0xf8, 0xd6, 0x17,
	0xae, 0x66, 0x78, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xad, 0x60, 0x0b, 0xc2, 0x00, 0x04, 0x00,
	0x00,
}
