// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/game_server/service.proto

package game_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameResultEnum int32

const (
	GameResultEnum_Win  GameResultEnum = 0
	GameResultEnum_Loss GameResultEnum = 1
)

var GameResultEnum_name = map[int32]string{
	0: "Win",
	1: "Loss",
}

var GameResultEnum_value = map[string]int32{
	"Win":  0,
	"Loss": 1,
}

func (x GameResultEnum) String() string {
	return proto.EnumName(GameResultEnum_name, int32(x))
}

func (GameResultEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{0}
}

type MoveResultEnum int32

const (
	MoveResultEnum_Ok    MoveResultEnum = 0
	MoveResultEnum_Retry MoveResultEnum = 1
	MoveResultEnum_Error MoveResultEnum = 2
)

var MoveResultEnum_name = map[int32]string{
	0: "Ok",
	1: "Retry",
	2: "Error",
}

var MoveResultEnum_value = map[string]int32{
	"Ok":    0,
	"Retry": 1,
	"Error": 2,
}

func (x MoveResultEnum) String() string {
	return proto.EnumName(MoveResultEnum_name, int32(x))
}

func (MoveResultEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{1}
}

type JoinResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResult) Reset()         { *m = JoinResult{} }
func (m *JoinResult) String() string { return proto.CompactTextString(m) }
func (*JoinResult) ProtoMessage()    {}
func (*JoinResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{0}
}

func (m *JoinResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResult.Unmarshal(m, b)
}
func (m *JoinResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResult.Marshal(b, m, deterministic)
}
func (m *JoinResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResult.Merge(m, src)
}
func (m *JoinResult) XXX_Size() int {
	return xxx_messageInfo_JoinResult.Size(m)
}
func (m *JoinResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResult.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResult proto.InternalMessageInfo

func (m *JoinResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *JoinResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinResult) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type UpdateGameStateResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGameStateResult) Reset()         { *m = UpdateGameStateResult{} }
func (m *UpdateGameStateResult) String() string { return proto.CompactTextString(m) }
func (*UpdateGameStateResult) ProtoMessage()    {}
func (*UpdateGameStateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{1}
}

func (m *UpdateGameStateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGameStateResult.Unmarshal(m, b)
}
func (m *UpdateGameStateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGameStateResult.Marshal(b, m, deterministic)
}
func (m *UpdateGameStateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGameStateResult.Merge(m, src)
}
func (m *UpdateGameStateResult) XXX_Size() int {
	return xxx_messageInfo_UpdateGameStateResult.Size(m)
}
func (m *UpdateGameStateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGameStateResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGameStateResult proto.InternalMessageInfo

type YourMoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YourMoveResult) Reset()         { *m = YourMoveResult{} }
func (m *YourMoveResult) String() string { return proto.CompactTextString(m) }
func (*YourMoveResult) ProtoMessage()    {}
func (*YourMoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{2}
}

func (m *YourMoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YourMoveResult.Unmarshal(m, b)
}
func (m *YourMoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YourMoveResult.Marshal(b, m, deterministic)
}
func (m *YourMoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YourMoveResult.Merge(m, src)
}
func (m *YourMoveResult) XXX_Size() int {
	return xxx_messageInfo_YourMoveResult.Size(m)
}
func (m *YourMoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_YourMoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_YourMoveResult proto.InternalMessageInfo

type GameFinishedResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameFinishedResult) Reset()         { *m = GameFinishedResult{} }
func (m *GameFinishedResult) String() string { return proto.CompactTextString(m) }
func (*GameFinishedResult) ProtoMessage()    {}
func (*GameFinishedResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{3}
}

func (m *GameFinishedResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameFinishedResult.Unmarshal(m, b)
}
func (m *GameFinishedResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameFinishedResult.Marshal(b, m, deterministic)
}
func (m *GameFinishedResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameFinishedResult.Merge(m, src)
}
func (m *GameFinishedResult) XXX_Size() int {
	return xxx_messageInfo_GameFinishedResult.Size(m)
}
func (m *GameFinishedResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameFinishedResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameFinishedResult proto.InternalMessageInfo

type GameResult struct {
	Result               GameResultEnum `protobuf:"varint,1,opt,name=result,proto3,enum=GameResultEnum" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GameResult) Reset()         { *m = GameResult{} }
func (m *GameResult) String() string { return proto.CompactTextString(m) }
func (*GameResult) ProtoMessage()    {}
func (*GameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{4}
}

func (m *GameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResult.Unmarshal(m, b)
}
func (m *GameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResult.Marshal(b, m, deterministic)
}
func (m *GameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResult.Merge(m, src)
}
func (m *GameResult) XXX_Size() int {
	return xxx_messageInfo_GameResult.Size(m)
}
func (m *GameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResult.DiscardUnknown(m)
}

var xxx_messageInfo_GameResult proto.InternalMessageInfo

func (m *GameResult) GetResult() GameResultEnum {
	if m != nil {
		return m.Result
	}
	return GameResultEnum_Win
}

type Position struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column               int32    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{5}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *Position) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type MoveResult struct {
	Result               MoveResultEnum `protobuf:"varint,1,opt,name=result,proto3,enum=MoveResultEnum" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MoveResult) Reset()         { *m = MoveResult{} }
func (m *MoveResult) String() string { return proto.CompactTextString(m) }
func (*MoveResult) ProtoMessage()    {}
func (*MoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c29bacf9357718, []int{6}
}

func (m *MoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResult.Unmarshal(m, b)
}
func (m *MoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResult.Marshal(b, m, deterministic)
}
func (m *MoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResult.Merge(m, src)
}
func (m *MoveResult) XXX_Size() int {
	return xxx_messageInfo_MoveResult.Size(m)
}
func (m *MoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResult proto.InternalMessageInfo

func (m *MoveResult) GetResult() MoveResultEnum {
	if m != nil {
		return m.Result
	}
	return MoveResultEnum_Ok
}

func init() {
	proto.RegisterEnum("GameResultEnum", GameResultEnum_name, GameResultEnum_value)
	proto.RegisterEnum("MoveResultEnum", MoveResultEnum_name, MoveResultEnum_value)
	proto.RegisterType((*JoinResult)(nil), "JoinResult")
	proto.RegisterType((*UpdateGameStateResult)(nil), "UpdateGameStateResult")
	proto.RegisterType((*YourMoveResult)(nil), "YourMoveResult")
	proto.RegisterType((*GameFinishedResult)(nil), "GameFinishedResult")
	proto.RegisterType((*GameResult)(nil), "GameResult")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*MoveResult)(nil), "MoveResult")
}

func init() {
	proto.RegisterFile("pkg/game_server/service.proto", fileDescriptor_92c29bacf9357718)
}

var fileDescriptor_92c29bacf9357718 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x93, 0xdd, 0x24, 0x66, 0xcf, 0x96, 0x6c, 0x38, 0xd6, 0x75, 0x89, 0x08, 0x4b, 0xbc,
	0xb0, 0x14, 0x9c, 0x40, 0xb4, 0x3e, 0x80, 0xb0, 0x0a, 0x62, 0xb5, 0x44, 0x44, 0xf4, 0xa6, 0xa4,
	0xed, 0x34, 0x0e, 0x9b, 0xcc, 0x84, 0xc9, 0xa4, 0xb2, 0xcf, 0xe4, 0x4b, 0xca, 0xe4, 0x83, 0x64,
	0x97, 0xed, 0x55, 0xce, 0x47, 0xce, 0xfc, 0xff, 0x67, 0x7e, 0x03, 0x2f, 0xcb, 0x6d, 0x16, 0x65,
	0x69, 0x41, 0xaf, 0x2b, 0x2a, 0x1f, 0xa8, 0x8c, 0xf4, 0x87, 0xdd, 0x52, 0x52, 0x4a, 0xa1, 0x44,
	0xf0, 0x22, 0x13, 0x22, 0xcb, 0x69, 0xd4, 0x64, 0x37, 0xf5, 0x7d, 0x44, 0x8b, 0x52, 0xed, 0xda,
	0x66, 0xf8, 0x15, 0xe0, 0xb3, 0x60, 0x3c, 0xa1, 0x55, 0x9d, 0x2b, 0x5c, 0x82, 0x23, 0x9b, 0x68,
	0x65, 0xae, 0xcd, 0x33, 0x37, 0xe9, 0x32, 0x3c, 0x05, 0x5b, 0x89, 0x2d, 0xe5, 0xab, 0xc9, 0xda,
	0x3c, 0x9b, 0x25, 0x6d, 0x82, 0x08, 0x16, 0xe3, 0xf7, 0x62, 0x35, 0x6d, 0x8a, 0x4d, 0x1c, 0x3e,
	0x87, 0x67, 0x3f, 0xca, 0xbb, 0x54, 0xd1, 0x4f, 0x69, 0x41, 0xbf, 0xab, 0x54, 0xd1, 0xf6, 0xe8,
	0xd0, 0x07, 0xef, 0x97, 0xa8, 0xe5, 0xa5, 0x78, 0xe8, 0x2b, 0xa7, 0x80, 0xfa, 0xa7, 0x8f, 0x8c,
	0xb3, 0xea, 0x0f, 0xbd, 0xeb, 0xaa, 0x17, 0x00, 0xba, 0xda, 0x19, 0x7a, 0xbd, 0x67, 0xc8, 0x8b,
	0x17, 0x64, 0x68, 0x6e, 0x78, 0x5d, 0xf4, 0x0e, 0xc3, 0x77, 0xe0, 0x5e, 0x89, 0x8a, 0x29, 0x26,
	0x38, 0xfa, 0x30, 0x95, 0xe2, 0x6f, 0x33, 0x61, 0x27, 0x3a, 0xd4, 0x7b, 0xdd, 0x8a, 0xbc, 0x2e,
	0xda, 0x05, 0xec, 0xa4, 0xcb, 0xb4, 0xd8, 0x60, 0xe8, 0x88, 0xd8, 0xd0, 0x1c, 0x8b, 0x9d, 0xbf,
	0x02, 0x6f, 0xdf, 0x06, 0x3e, 0x81, 0xe9, 0x4f, 0xc6, 0x7d, 0x03, 0x5d, 0xb0, 0xbe, 0x88, 0xaa,
	0xf2, 0xcd, 0x73, 0x02, 0xde, 0xfe, 0x38, 0x3a, 0x30, 0xf9, 0xb6, 0xf5, 0x0d, 0x9c, 0x81, 0x9d,
	0x50, 0x25, 0x77, 0xbe, 0xa9, 0xc3, 0x8d, 0x94, 0x42, 0xfa, 0x93, 0xf8, 0x1a, 0x4e, 0xf4, 0xa1,
	0xd5, 0x65, 0xca, 0xd3, 0x8c, 0x4a, 0x7c, 0x03, 0x96, 0x26, 0x83, 0x4b, 0xd2, 0xf2, 0x23, 0x3d,
	0x3f, 0xb2, 0xd1, 0xfc, 0x82, 0x39, 0x19, 0xc0, 0x85, 0x06, 0xae, 0xc1, 0xd2, 0x72, 0x38, 0x23,
	0xfd, 0x3d, 0x04, 0xf3, 0x91, 0xff, 0xd0, 0x88, 0xff, 0x99, 0xe0, 0x5c, 0xe5, 0xe9, 0x8e, 0x4a,
	0x7c, 0x0f, 0x8b, 0x03, 0x4a, 0xe3, 0xb9, 0x25, 0x39, 0x8e, 0xd0, 0xc0, 0x0b, 0x70, 0x7b, 0x88,
	0x8f, 0xfa, 0x5a, 0x90, 0x03, 0xce, 0x06, 0xc6, 0xed, 0x6a, 0x3d, 0x69, 0x9c, 0x8f, 0x28, 0x06,
	0x4f, 0xc9, 0x91, 0x57, 0x60, 0x7c, 0xf0, 0x7e, 0x9f, 0x8c, 0xdf, 0xf4, 0x8d, 0xd3, 0xc8, 0xbc,
	0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x32, 0x67, 0x82, 0x21, 0xed, 0x02, 0x00, 0x00,
}
